jdi homework completed
Dr-Java/AnastasiaEgorova pull request #7
Opened 2021-08-28 17:17 UTC by Dr-Java

2021-09-01 16:55 UTC, pnatashap requested changes
Comments are in code

2021-09-01 16:55 UTC, pnatashap commented on pom.xml
> +        <jdi-light-html.version>1.2.19</jdi-light-html.version>
It's better to use the latest library version, 1.3.13 or 1.3.14

2021-09-01 16:55 UTC, pnatashap commented on src/main/java/com/epam/tc/hw7jdi/JdiSite.java
> +    public static void open() {
This method is not usefull: initSite opens Site by default.

2021-09-01 16:55 UTC, pnatashap commented on src/main/java/com/epam/tc/hw7jdi/entities/User.java
> +public class User {
Should extend DataClass

2021-09-01 16:55 UTC, pnatashap commented on src/main/java/com/epam/tc/hw7jdi/entities/MetalsAndColors.java
> +public class MetalsAndColors {
Should extend DataClass

2021-09-01 16:55 UTC, pnatashap commented on src/main/java/com/epam/tc/hw7jdi/forms/MetalsAndColorsForm.java
> +        var vegetablesFromDropdown = "vegetables";
variable is not usefull at this place

2021-09-01 16:55 UTC, pnatashap commented on src/main/java/com/epam/tc/hw7jdi/forms/MetalsAndColorsForm.java
> +    public void clickSubmitButton() {
there is an existing method submit for this functionality

2021-09-01 16:55 UTC, pnatashap commented on src/main/java/com/epam/tc/hw7jdi/pages/JdiHomePage.java
> +    public void openMetalsColorsPage() {
Not a good place for this function. It can be used not only from HomePage, but available only for it

2021-09-01 16:55 UTC, pnatashap commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +    public void testSuccessfulLogin() {
The order for tests is not predictable at all, for example, the second test can be executed first and fail due to missing login. Or we can run tests in parallel and the second one will fail in this case.

2021-09-01 16:55 UTC, pnatashap commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +        JdiSite.openMetalsColorsPage();
There is no login precondition

2021-09-01 16:55 UTC, pnatashap commented on src/main/java/com/epam/tc/hw7jdi/pages/MetalsAndColorsPage.java
> +        doesSummaryLogRowContain(metalsAndColors.getSummary().get(0),
It's very difficult way to check data and not very stable.
It's easier to get all text from Result box and check that they are equal to expected text.

2021-09-03 06:50 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/JdiSite.java
> +    public static void open() {
Thanks. I’ve tried not to use this method. But it doesn’t work for me (runtime exception occurs).

2021-09-03 06:57 UTC, Dr-Java commented on pom.xml
> +        <jdi-light-html.version>1.2.19</jdi-light-html.version>
Thanks. Both of these versions don’t work for me. Every time I try, I get runtime exception with message: “Can’t get WebDriver: chrome”.

2021-09-03 06:59 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/entities/User.java
> +public class User {
Thanks. Will be done!

2021-09-03 06:59 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/entities/MetalsAndColors.java
> +public class MetalsAndColors {
Thanks. Will be done!

2021-09-03 06:59 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/forms/MetalsAndColorsForm.java
> +        var vegetablesFromDropdown = "vegetables";
Thanks. Will be removed!

2021-09-03 07:00 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/forms/MetalsAndColorsForm.java
> +    public void clickSubmitButton() {
Thanks. Will be done!

2021-09-03 07:01 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/pages/JdiHomePage.java
> +    public void openMetalsColorsPage() {
Thanks. Could you please tell me, where is an ideal place for this function?

2021-09-03 07:02 UTC, Dr-Java commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +    public void testSuccessfulLogin() {
Thanks. Very useful information for me!

2021-09-03 07:32 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/pages/MetalsAndColorsPage.java
> +        doesSummaryLogRowContain(metalsAndColors.getSummary().get(0),
Thanks. Yes, I found better solution.

2021-09-03 07:33 UTC, Dr-Java commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +        JdiSite.openMetalsColorsPage();
Thanks. Guess I have to move login to before suite method.

2021-09-03 09:18 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/entities/User.java
> +public class User {
Fixed

2021-09-03 09:18 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/entities/MetalsAndColors.java
> +public class MetalsAndColors {
Fixed

2021-09-03 09:18 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/forms/MetalsAndColorsForm.java
> +        var vegetablesFromDropdown = "vegetables";
Fixed

2021-09-03 09:18 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/forms/MetalsAndColorsForm.java
> +    public void clickSubmitButton() {
Fixed

2021-09-03 09:19 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/pages/JdiHomePage.java
> +    public void openMetalsColorsPage() {
Fixed

2021-09-03 09:19 UTC, Dr-Java commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +    public void testSuccessfulLogin() {
Fixed

2021-09-03 09:19 UTC, Dr-Java commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +        JdiSite.openMetalsColorsPage();
Fixed

2021-09-03 09:19 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/pages/MetalsAndColorsPage.java
> +        doesSummaryLogRowContain(metalsAndColors.getSummary().get(0),
Fixed

2021-09-10 21:28 UTC, pnatashap requested changes
comments are in code

2021-09-10 21:28 UTC, pnatashap commented on src/main/java/com/epam/tc/hw7jdi/forms/MetalsAndColorsForm.java
> +    private void deselectVegetables() {
Additional function with one line is not good at this place

2021-09-10 21:28 UTC, pnatashap commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +        soft.assertThat(JdiSite.metalsAndColorsPage.title)
Wrong softAssert usage. 
If we open page which is not Metals and Color - we cann't go wtih filling Form and other checks

2021-09-10 21:28 UTC, pnatashap commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +        soft.assertThat(JdiSite.getUserName())
This assert should not be their, it's a precondition for test.

2021-09-11 10:55 UTC, Dr-Java commented on src/main/java/com/epam/tc/hw7jdi/forms/MetalsAndColorsForm.java
> +    private void deselectVegetables() {
Thanks. Function was removed.

2021-09-11 10:56 UTC, Dr-Java commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +        soft.assertThat(JdiSite.metalsAndColorsPage.title)
Thanks! I've found better solution.

2021-09-11 10:59 UTC, Dr-Java commented on src/test/java/com/epam/tc/egorova/hw7jdi/tests/JdiTests.java
> +        soft.assertThat(JdiSite.getUserName())
Thanks. Guess I had to create an additional method to check if user was loggined. But I still have no idea about an ideal place for this assertion. Maybe I could move it to BeforeSuite method?

2021-09-22 18:35 UTC, pnatashap approved these changes

2021-09-22 18:35 UTC, pnatashap commented on src/test/java/com/epam/tc/egorova/hw7jdi/dataprovider/JdiTestDataProvider.java
> +import java.util.List;
Not used import

2021-09-23 14:47 UTC, merged